### ISSUE TITLE
Case insensitive parsing of string

### ISSUE THREAD

**Issue by Natim** [terezka/yaml#1]
I tried to parse the following YAML:

```
  - name: GARLIC
    units: 
      - clove
      - grams
  - name: "GARLIC POWDER"
    units: 
      - grams
```

For some reasons `GARLIC` is parsed as `garlic` (lowercase) while `GARLIC POWDER` is parsed in uppercase.

As a fix, I used the following parser:

```
(Decode.field "name"
    (Decode.string
        |> Decode.andThen (String.toUpper >> Decode.succeed)
    )
)
```
